version: "3.5"

services:
  admin:
    stdin_open: true
    image: node:12
    volumes:
      - ./admin:/usr/src/admin
    environment:
      REACT_APP_API_ENTRYPOINT: http://vulcain:80
    ports:
      - 3000:3000
    working_dir: /usr/src/admin
    command: yarn start

  cypress:
    image: cypress/included:4.10.0
    depends_on:
      - admin
      - vulcain
      - api
    volumes:
      - ./tests:/app
    working_dir: /app
    links:
      - "admin:admin"
      - "vulcain:vulcain"
    entrypoint: yarn run wait-and-test

